# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  jvm:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc zlib1g-dev make lsb-release file
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Run JVM tests
          command: |
            lein test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

  linux:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      GRAALVM_HOME: /home/circleci/graalvm-ce-java11-20.1.0
    #resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Clojure
          command: |
            wget https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc zlib1g-dev make
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-20.1.0 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
              tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
            fi
            $GRAALVM_HOME/bin/gu install native-image
      - run:
          name: Build binary and test
          command: |
            make clean test-bin GRAALVM_HOME=$GRAALVM_HOME
          no_output_timeout: 40m
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java11-20.1.0-dev
          key: linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: build
          destination: build

  mac:
    macos:
      xcode: "10.0"
    environment:
      GRAALVM_HOME: /Users/distiller/graalvm-ce-java11-20.1.0/Contents/Home
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Clojure
          command: |
            .circleci/script/install-clojure /usr/local
      - run:
          name: Install Leiningen
          command: |
            .circleci/script/install-leiningen
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-20.1.0 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz
              tar xzf graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz
            fi
            $GRAALVM_HOME/bin/gu install native-image
          no_output_timeout: 30m
      - run:
          name: Build binary and test
          command: |
            make clean test-bin GRAALVM_HOME=$GRAALVM_HOME
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java11-20.1.0-dev
          key: mac-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: build
          destination: build
      # - store_artifacts:
      #     path: target/uberjar
      #     destination: target/uberjar


workflows:
  version: 2
  ci:
    jobs:
      - jvm:
          filters:
            branches:
              only: master

      - mac:
          filters:
            branches:
              only: master

      # build on free circleci account runs out of ram
      # Error: Image build request failed with exit status 137
      - linux:
          filters:
            branches:
              only: master
